
export const GET_PARTICIPATED_SUCCESS = "GET_PARTICIPATED_SUCCESS";
export const GET_PARTICIPATED_FAILURE = "GET_PARTICIPATED_FAILURE";
export const GET_PARTICIPATED_REQUEST = "GET_PARTICIPATED_REQUEST";

