

export const GOOGLE_EVENT_SUCCESS = "GOOGLE_EVENT_SUCCESS";
export const GOOGLE_EVENT_FAILURE = "GOOGLE_EVENT_FAILURE";
export const GOOGLE_EVENT_REQUEST = "GOOGLE_EVENT_REQUEST";
export const SINGLE_GOOGLE_EVENT_REQUEST = "SINGLE_GOOGLE_EVENT_REQUEST";
export const SINGLE_GOOGLE_EVENT_FAILURE = "SINGLE_GOOGLE_EVENT_FAILURE";
export const SINGLE_GOOGLE_EVENT_SUCCESS = "SINGLE_GOOGLE_EVENT_SUCCESS";


