
export const GET_PARTICIPANTS_SUCCESS = "GET_PARTICIPANTS_SUCCESS";
export const GET_PARTICIPANTS_FAILURE = "GET_PARTICIPANTS_FAILURE";
export const GET_PARTICIPANTS_REQUEST = "GET_PARTICIPANTS_REQUEST";

export const SENDMAIL_REQUEST = "SENDMAIL_REQUEST";
export const SENDMAIL_SUCCESS = "SENDMAIL_SUCCESS";
export const SENDMAIL_FAILURE = "SENDMAIL_FAILURE";

