// get

export const FETCH_TESTIMONIAL_DATA = "FETCH_TESTIMONIAL_DATA";
export const TESTIMONIAL_ERROR = "TESTIMONIAL_ERROR";
export const TESTIMONIAL_REQUEST = "TESTIMONIAL_REQUEST";

// post
export const POST_TESTIMONIAL_DATA = "POST_TESTIMONIAL_DATA";